apiVersion: apps/v1
kind: Deployment
metadata:
  creationTimestamp: null
  labels:
    app: jimmyjohns
  name: jimmyjohns
spec:
  replicas: 3
  selector:
    matchLabels:
      app: jimmyjohns
  strategy: {}
  template:
    metadata:
      creationTimestamp: null
      labels:
        app: jimmyjohns
    spec:
      containers:
        - image: httpd:alpine3.18
          name: httpd
  strategy:
    type: RollingUpdate
    rollingUpdate:
      maxUnavailable: 1
      maxSurge: 1
